// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pustok.Models;

#nullable disable

namespace Pustok.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pustok.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(1988),
                            IsActive = true,
                            Name = "Arts & Photography"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2000),
                            IsActive = true,
                            Name = "Biographies"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2002),
                            IsActive = true,
                            Name = "Business & Money"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2003),
                            IsActive = true,
                            Name = "Children's Books"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2033),
                            IsActive = true,
                            Name = "Comics"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2035),
                            IsActive = true,
                            Name = "Cookbooks"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2036),
                            IsActive = true,
                            Name = "Education"
                        });
                });

            modelBuilder.Entity("Pustok.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<string>("HoverImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SaleEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SalesCount")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author 1",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2152),
                            Description = "This is a great book about topic 1. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 21,
                            HoverImagePath = "product-3.jpg",
                            ISBN = "978-1-1001-101-1",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = false,
                            IsOnSale = true,
                            Language = "English",
                            MainImagePath = "product-2.jpg",
                            Name = "Book Title 1",
                            OldPrice = 57m,
                            PageCount = 210,
                            Price = 35m,
                            PublishDate = new DateTime(2024, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2208),
                            Publisher = "Publisher 1",
                            Rating = 4.1m,
                            ReviewCount = 5,
                            SKU = "BK1001",
                            SaleEndDate = new DateTime(2026, 1, 9, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2223),
                            SalesCount = 2,
                            StockQuantity = 51,
                            ViewCount = 10,
                            Weight = 0.6m
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author 2",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2238),
                            Description = "This is a great book about topic 2. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 22,
                            HoverImagePath = "product-4.jpg",
                            ISBN = "978-2-1002-102-2",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = false,
                            IsOnSale = true,
                            Language = "English",
                            MainImagePath = "product-3.jpg",
                            Name = "Book Title 2",
                            OldPrice = 64m,
                            PageCount = 220,
                            Price = 40m,
                            PublishDate = new DateTime(2023, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2244),
                            Publisher = "Publisher 2",
                            Rating = 4.2m,
                            ReviewCount = 10,
                            SKU = "BK1002",
                            SaleEndDate = new DateTime(2026, 1, 9, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2247),
                            SalesCount = 4,
                            StockQuantity = 52,
                            ViewCount = 20,
                            Weight = 0.7m
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author 3",
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2256),
                            Description = "This is a great book about topic 3. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 23,
                            HoverImagePath = "product-5.jpg",
                            ISBN = "978-3-1003-103-3",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = true,
                            IsOnSale = true,
                            Language = "English",
                            MainImagePath = "product-4.jpg",
                            Name = "Book Title 3",
                            OldPrice = 71m,
                            PageCount = 230,
                            Price = 45m,
                            PublishDate = new DateTime(2022, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2263),
                            Publisher = "Publisher 3",
                            Rating = 4.3m,
                            ReviewCount = 15,
                            SKU = "BK1003",
                            SaleEndDate = new DateTime(2026, 1, 9, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2264),
                            SalesCount = 6,
                            StockQuantity = 53,
                            ViewCount = 30,
                            Weight = 0.8m
                        },
                        new
                        {
                            Id = 4,
                            Author = "Author 4",
                            CategoryId = 5,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2273),
                            Description = "This is a great book about topic 4. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 24,
                            HoverImagePath = "product-6.jpg",
                            ISBN = "978-4-1004-104-4",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = false,
                            IsOnSale = true,
                            Language = "English",
                            MainImagePath = "product-5.jpg",
                            Name = "Book Title 4",
                            OldPrice = 78m,
                            PageCount = 240,
                            Price = 50m,
                            PublishDate = new DateTime(2021, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2278),
                            Publisher = "Publisher 4",
                            Rating = 4.4m,
                            ReviewCount = 20,
                            SKU = "BK1004",
                            SaleEndDate = new DateTime(2026, 1, 9, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2279),
                            SalesCount = 8,
                            StockQuantity = 54,
                            ViewCount = 40,
                            Weight = 0.9m
                        },
                        new
                        {
                            Id = 5,
                            Author = "Author 5",
                            CategoryId = 6,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2288),
                            Description = "This is a great book about topic 5. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 20,
                            HoverImagePath = "product-7.jpg",
                            ISBN = "978-5-1005-105-5",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = false,
                            IsOnSale = true,
                            Language = "English",
                            MainImagePath = "product-6.jpg",
                            Name = "Book Title 5",
                            OldPrice = 85m,
                            PageCount = 250,
                            Price = 55m,
                            PublishDate = new DateTime(2020, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2294),
                            Publisher = "Publisher 5",
                            Rating = 4.5m,
                            ReviewCount = 25,
                            SKU = "BK1005",
                            SaleEndDate = new DateTime(2026, 1, 9, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2296),
                            SalesCount = 10,
                            StockQuantity = 55,
                            ViewCount = 50,
                            Weight = 1.0m
                        },
                        new
                        {
                            Id = 6,
                            Author = "Author 6",
                            CategoryId = 7,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2305),
                            Description = "This is a great book about topic 6. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 21,
                            HoverImagePath = "product-8.jpg",
                            ISBN = "978-6-1006-106-6",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = true,
                            IsOnSale = true,
                            Language = "English",
                            MainImagePath = "product-7.jpg",
                            Name = "Book Title 6",
                            OldPrice = 92m,
                            PageCount = 260,
                            Price = 60m,
                            PublishDate = new DateTime(2019, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2311),
                            Publisher = "Publisher 6",
                            Rating = 4.6m,
                            ReviewCount = 30,
                            SKU = "BK1006",
                            SaleEndDate = new DateTime(2026, 1, 9, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2312),
                            SalesCount = 12,
                            StockQuantity = 56,
                            ViewCount = 60,
                            Weight = 1.1m
                        },
                        new
                        {
                            Id = 7,
                            Author = "Author 7",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2352),
                            Description = "This is a great book about topic 7. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 22,
                            HoverImagePath = "product-9.jpg",
                            ISBN = "978-7-1007-107-7",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = false,
                            IsOnSale = true,
                            Language = "English",
                            MainImagePath = "product-8.jpg",
                            Name = "Book Title 7",
                            OldPrice = 99m,
                            PageCount = 270,
                            Price = 65m,
                            PublishDate = new DateTime(2018, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2358),
                            Publisher = "Publisher 7",
                            Rating = 4.7m,
                            ReviewCount = 35,
                            SKU = "BK1007",
                            SaleEndDate = new DateTime(2026, 1, 9, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2360),
                            SalesCount = 14,
                            StockQuantity = 57,
                            ViewCount = 70,
                            Weight = 1.2m
                        },
                        new
                        {
                            Id = 8,
                            Author = "Author 8",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2369),
                            Description = "This is a great book about topic 8. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 23,
                            HoverImagePath = "product-10.jpg",
                            ISBN = "978-8-1008-108-8",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = false,
                            IsOnSale = false,
                            Language = "English",
                            MainImagePath = "product-9.jpg",
                            Name = "Book Title 8",
                            OldPrice = 106m,
                            PageCount = 280,
                            Price = 70m,
                            PublishDate = new DateTime(2017, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2375),
                            Publisher = "Publisher 8",
                            Rating = 4.8m,
                            ReviewCount = 40,
                            SKU = "BK1008",
                            SalesCount = 16,
                            StockQuantity = 58,
                            ViewCount = 80,
                            Weight = 1.3m
                        },
                        new
                        {
                            Id = 9,
                            Author = "Author 9",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2384),
                            Description = "This is a great book about topic 9. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 24,
                            HoverImagePath = "product-11.jpg",
                            ISBN = "978-9-1009-109-9",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = true,
                            IsOnSale = false,
                            Language = "English",
                            MainImagePath = "product-10.jpg",
                            Name = "Book Title 9",
                            OldPrice = 113m,
                            PageCount = 290,
                            Price = 75m,
                            PublishDate = new DateTime(2016, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2390),
                            Publisher = "Publisher 9",
                            Rating = 4.9m,
                            ReviewCount = 45,
                            SKU = "BK1009",
                            SalesCount = 18,
                            StockQuantity = 59,
                            ViewCount = 90,
                            Weight = 1.4m
                        },
                        new
                        {
                            Id = 10,
                            Author = "Author 10",
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2401),
                            Description = "This is a great book about topic 10. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 20,
                            HoverImagePath = "product-12.jpg",
                            ISBN = "978-10-1010-110-10",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = false,
                            IsOnSale = false,
                            Language = "English",
                            MainImagePath = "product-11.jpg",
                            Name = "Book Title 10",
                            OldPrice = 120m,
                            PageCount = 300,
                            Price = 80m,
                            PublishDate = new DateTime(2015, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2407),
                            Publisher = "Publisher 10",
                            Rating = 4.0m,
                            ReviewCount = 50,
                            SKU = "BK1010",
                            SalesCount = 20,
                            StockQuantity = 60,
                            ViewCount = 100,
                            Weight = 1.5m
                        },
                        new
                        {
                            Id = 11,
                            Author = "Author 11",
                            CategoryId = 5,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2417),
                            Description = "This is a great book about topic 11. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 21,
                            HoverImagePath = "product-13.jpg",
                            ISBN = "978-11-1011-111-11",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = false,
                            IsOnSale = false,
                            Language = "English",
                            MainImagePath = "product-12.jpg",
                            Name = "Book Title 11",
                            OldPrice = 127m,
                            PageCount = 310,
                            Price = 85m,
                            PublishDate = new DateTime(2014, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2422),
                            Publisher = "Publisher 11",
                            Rating = 4.1m,
                            ReviewCount = 55,
                            SKU = "BK1011",
                            SalesCount = 22,
                            StockQuantity = 61,
                            ViewCount = 110,
                            Weight = 1.6m
                        },
                        new
                        {
                            Id = 12,
                            Author = "Author 12",
                            CategoryId = 6,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2431),
                            Description = "This is a great book about topic 12. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 22,
                            HoverImagePath = "product-1.jpg",
                            ISBN = "978-12-1012-112-12",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = true,
                            IsOnSale = false,
                            Language = "English",
                            MainImagePath = "product-13.jpg",
                            Name = "Book Title 12",
                            OldPrice = 134m,
                            PageCount = 320,
                            Price = 90m,
                            PublishDate = new DateTime(2013, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2437),
                            Publisher = "Publisher 12",
                            Rating = 4.2m,
                            ReviewCount = 60,
                            SKU = "BK1012",
                            SalesCount = 24,
                            StockQuantity = 62,
                            ViewCount = 120,
                            Weight = 1.7m
                        },
                        new
                        {
                            Id = 13,
                            Author = "Author 13",
                            CategoryId = 7,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2446),
                            Description = "This is a great book about topic 13. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 23,
                            HoverImagePath = "product-2.jpg",
                            ISBN = "978-13-1013-113-13",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = false,
                            IsOnSale = false,
                            Language = "English",
                            MainImagePath = "product-1.jpg",
                            Name = "Book Title 13",
                            OldPrice = 141m,
                            PageCount = 330,
                            Price = 95m,
                            PublishDate = new DateTime(2012, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2485),
                            Publisher = "Publisher 13",
                            Rating = 4.3m,
                            ReviewCount = 65,
                            SKU = "BK1013",
                            SalesCount = 26,
                            StockQuantity = 63,
                            ViewCount = 130,
                            Weight = 1.8m
                        },
                        new
                        {
                            Id = 14,
                            Author = "Author 14",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2495),
                            Description = "This is a great book about topic 14. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 24,
                            HoverImagePath = "product-3.jpg",
                            ISBN = "978-14-1014-114-14",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = false,
                            IsOnSale = false,
                            Language = "English",
                            MainImagePath = "product-2.jpg",
                            Name = "Book Title 14",
                            OldPrice = 148m,
                            PageCount = 340,
                            Price = 100m,
                            PublishDate = new DateTime(2011, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2502),
                            Publisher = "Publisher 14",
                            Rating = 4.4m,
                            ReviewCount = 70,
                            SKU = "BK1014",
                            SalesCount = 28,
                            StockQuantity = 64,
                            ViewCount = 140,
                            Weight = 1.9m
                        },
                        new
                        {
                            Id = 15,
                            Author = "Author 15",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2511),
                            Description = "This is a great book about topic 15. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 20,
                            HoverImagePath = "product-4.jpg",
                            ISBN = "978-15-1015-115-15",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = true,
                            IsOnSale = false,
                            Language = "English",
                            MainImagePath = "product-3.jpg",
                            Name = "Book Title 15",
                            OldPrice = 155m,
                            PageCount = 350,
                            Price = 105m,
                            PublishDate = new DateTime(2010, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2517),
                            Publisher = "Publisher 15",
                            Rating = 4.5m,
                            ReviewCount = 75,
                            SKU = "BK1015",
                            SalesCount = 30,
                            StockQuantity = 65,
                            ViewCount = 150,
                            Weight = 2.0m
                        },
                        new
                        {
                            Id = 16,
                            Author = "Author 16",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2527),
                            Description = "This is a great book about topic 16. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 21,
                            HoverImagePath = "product-5.jpg",
                            ISBN = "978-16-1016-116-16",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = false,
                            IsOnSale = false,
                            Language = "English",
                            MainImagePath = "product-4.jpg",
                            Name = "Book Title 16",
                            OldPrice = 162m,
                            PageCount = 360,
                            Price = 110m,
                            PublishDate = new DateTime(2009, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2532),
                            Publisher = "Publisher 16",
                            Rating = 4.6m,
                            ReviewCount = 80,
                            SKU = "BK1016",
                            SalesCount = 32,
                            StockQuantity = 66,
                            ViewCount = 160,
                            Weight = 2.1m
                        },
                        new
                        {
                            Id = 17,
                            Author = "Author 17",
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2542),
                            Description = "This is a great book about topic 17. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 22,
                            HoverImagePath = "product-6.jpg",
                            ISBN = "978-17-1017-117-17",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = false,
                            IsOnSale = false,
                            Language = "English",
                            MainImagePath = "product-5.jpg",
                            Name = "Book Title 17",
                            OldPrice = 169m,
                            PageCount = 370,
                            Price = 115m,
                            PublishDate = new DateTime(2008, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2547),
                            Publisher = "Publisher 17",
                            Rating = 4.7m,
                            ReviewCount = 85,
                            SKU = "BK1017",
                            SalesCount = 34,
                            StockQuantity = 67,
                            ViewCount = 170,
                            Weight = 2.2m
                        },
                        new
                        {
                            Id = 18,
                            Author = "Author 18",
                            CategoryId = 5,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2557),
                            Description = "This is a great book about topic 18. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 23,
                            HoverImagePath = "product-7.jpg",
                            ISBN = "978-18-1018-118-18",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = true,
                            IsOnSale = false,
                            Language = "English",
                            MainImagePath = "product-6.jpg",
                            Name = "Book Title 18",
                            OldPrice = 176m,
                            PageCount = 380,
                            Price = 120m,
                            PublishDate = new DateTime(2007, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2563),
                            Publisher = "Publisher 18",
                            Rating = 4.8m,
                            ReviewCount = 90,
                            SKU = "BK1018",
                            SalesCount = 36,
                            StockQuantity = 68,
                            ViewCount = 180,
                            Weight = 2.3m
                        },
                        new
                        {
                            Id = 19,
                            Author = "Author 19",
                            CategoryId = 6,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2572),
                            Description = "This is a great book about topic 19. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 24,
                            HoverImagePath = "product-8.jpg",
                            ISBN = "978-19-1019-119-19",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = false,
                            IsOnSale = false,
                            Language = "English",
                            MainImagePath = "product-7.jpg",
                            Name = "Book Title 19",
                            OldPrice = 183m,
                            PageCount = 390,
                            Price = 125m,
                            PublishDate = new DateTime(2006, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2577),
                            Publisher = "Publisher 19",
                            Rating = 4.9m,
                            ReviewCount = 95,
                            SKU = "BK1019",
                            SalesCount = 38,
                            StockQuantity = 69,
                            ViewCount = 190,
                            Weight = 2.4m
                        },
                        new
                        {
                            Id = 20,
                            Author = "Author 20",
                            CategoryId = 7,
                            CreatedDate = new DateTime(2025, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2614),
                            Description = "This is a great book about topic 20. Long printed dress with thin adjustable straps. V-neckline and wiring under the Dust with ruffles at the bottom of the dress.",
                            Dimensions = "8.5 x 0.5 x 11 inches",
                            DiscountPercentage = 20,
                            HoverImagePath = "product-9.jpg",
                            ISBN = "978-20-1020-120-20",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = false,
                            IsOnSale = false,
                            Language = "English",
                            MainImagePath = "product-8.jpg",
                            Name = "Book Title 20",
                            OldPrice = 190m,
                            PageCount = 400,
                            Price = 130m,
                            PublishDate = new DateTime(2005, 12, 10, 2, 5, 41, 496, DateTimeKind.Local).AddTicks(2620),
                            Publisher = "Publisher 20",
                            Rating = 4.0m,
                            ReviewCount = 100,
                            SKU = "BK1020",
                            SalesCount = 40,
                            StockQuantity = 70,
                            ViewCount = 200,
                            Weight = 2.5m
                        });
                });

            modelBuilder.Entity("Pustok.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Pustok.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextAlignment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("Pustok.Models.Category", b =>
                {
                    b.HasOne("Pustok.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Pustok.Models.Product", b =>
                {
                    b.HasOne("Pustok.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Pustok.Models.ProductImage", b =>
                {
                    b.HasOne("Pustok.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Pustok.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Pustok.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
